version: '3.8'

services:
  task-board:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
#      SPRING_DATASOURCE_URL: jdbc:h2:file:/app/data/vm1
#      SPRING_DATASOURCE_USERNAME: sa
#      SPRING_DATASOURCE_PASSWORD: password
#      SPRING_JPA_HIBERNATE_DDL_AUsTO: update